
project_id = "kwnwhgucnzqxndzjayyq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
secure_port = 54324

[studio]
enabled = true
api_url = "http://127.0.0.1:54321"
port = 54323

[inbucket]
enabled = true
port = 54324
pop3_port = 54325
smtp_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54327
inspector_port = 54328

[functions.transcribe-audio]
verify_jwt = true

[functions.smart-query-planner]
verify_jwt = true

[functions.chat-with-rag]
verify_jwt = true

[functions.gpt-response-consolidator]
verify_jwt = false

[functions.generate-analysis-themes]
verify_jwt = true

[functions.generate-emotions-for-entries]
verify_jwt = true

[functions.sentiment-analysis-batcher]
verify_jwt = true

[functions.ensure-chat-persistence]
verify_jwt = true

[functions.test-google-nlapi]
verify_jwt = false

[functions.transcribe-chat-audio]
verify_jwt = true
