
project_id = "kwnwhgucnzqxndzjayyq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
secure_port = 54324

[studio]
enabled = true
api_url = "http://127.0.0.1:54321"
port = 54323

[inbucket]
enabled = true
port = 54324
pop3_port = 54325
smtp_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54327
inspector_port = 54328

[functions.analyze-emotions]
verify_jwt = true

[functions.analyze-sentiment]
verify_jwt = true

[functions.batch-analyze-sentiment]
verify_jwt = true

[functions.batch-extract-entities]
verify_jwt = true

[functions.chat-query-classifier]
verify_jwt = true

[functions.chat-rag]
verify_jwt = true

[functions.chat-with-rag]
verify_jwt = true

[functions.combine-segment-responses]
verify_jwt = true

[functions.debug-rag-pipeline]
verify_jwt = true

[functions.ensure-chat-persistence]
verify_jwt = true

[functions.general-mental-health-chat]
verify_jwt = true

[functions.generate-missing-embeddings]
verify_jwt = true

[functions.generate-streaming-messages]
verify_jwt = true

[functions.generate-themes]
verify_jwt = true

[functions.gpt-clarification-generator]
verify_jwt = true

[functions.gpt-master-orchestrator]
verify_jwt = true

[functions.gpt-response-consolidator]
verify_jwt = false

[functions.gpt-search-orchestrator]
verify_jwt = true

[functions.inspirational-quotes]
verify_jwt = false

[functions.intelligent-query-planner]
verify_jwt = true

[functions.journal-summary]
verify_jwt = true

[functions.message-classification-monitor]
verify_jwt = true

[functions.message-persistence-monitor]
verify_jwt = true

[functions.revenuecat-init]
verify_jwt = true

[functions.revenuecat-purchase]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.segment-complex-query]
verify_jwt = true

[functions.set-api-key]
verify_jwt = true

[functions.smart-query-planner]
verify_jwt = true

[functions.temporary]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.transcribe-chat-audio]
verify_jwt = true

[functions.translate-static-content]
verify_jwt = true

[functions.translate-text]
verify_jwt = true
