
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "kwnwhgucnzqxndzjayyq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
webhook_port = 54323

[studio]
enabled = true
port = 54324
api_url = "https://supabase.lovable.dev"

[inbucket]
enabled = false
port = 54325

[storage]
enabled = false
port = 54328

[functions]
port = 54326
serve_port = 54327

# Enhanced intelligent edge functions with database schema awareness
[functions.analyze-emotions]
verify_jwt = true

[functions.analyze-sentiment]
verify_jwt = true

[functions.batch-analyze-sentiment]
verify_jwt = true

[functions.batch-extract-entities]
verify_jwt = true

[functions.chat-query-classifier]
verify_jwt = true

[functions.chat-with-rag]
verify_jwt = true

[functions.combine-segment-responses]
verify_jwt = true

[functions.generate-missing-embeddings]
verify_jwt = true

[functions.gpt-master-orchestrator]
verify_jwt = true

[functions.gpt-search-orchestrator]
verify_jwt = true

[functions.inspirational-quotes]
verify_jwt = false

[functions.intelligent-query-planner]
verify_jwt = true

[functions.intelligent-response-generator]
verify_jwt = true

[functions.journal-summary]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.segment-complex-query]
verify_jwt = true

[functions.set-api-key]
verify_jwt = true

[functions.smart-chat]
verify_jwt = true

[functions.smart-query-planner]
verify_jwt = true

[functions.translate-text]
verify_jwt = false
