
project_id = "kwnwhgucnzqxndzjayyq"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[realtime]
webhooks = []

[functions]
serve_port = 54328
function_port = 54321

[[functions.smart-query-planner]]
verify_jwt = false
port = 54321

[[functions.ensure-chat-persistence]]
verify_jwt = false
port = 54321
