
project_id = "supabase"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["https://127.0.0.1:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.microsoft]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions]
[functions.smart-query-orchestrator]
port = 54345
verify_jwt = true
