
import React, { createContext, useContext, useState, useEffect } from 'react';

// Define supported languages
export const SUPPORTED_LANGUAGES = {
  en: { name: 'English', code: 'en' },
  es: { name: 'Español', code: 'es' },
  fr: { name: 'Français', code: 'fr' },
  de: { name: 'Deutsch', code: 'de' },
  zh: { name: '中文', code: 'zh' },
  hi: { name: 'हिन्दी', code: 'hi' },
  ja: { name: '日本語', code: 'ja' },
  ko: { name: '한국어', code: 'ko' },
  ru: { name: 'Русский', code: 'ru' },
  pt: { name: 'Português', code: 'pt' }
};

export type LanguageCode = keyof typeof SUPPORTED_LANGUAGES;

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  translate: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translations object - in a real app, this would be loaded from a translations file
// or fetched from a translation service
const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Common website and app translations
    'app.download': 'Download',
    'app.tryWebApp': 'Try Web App',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'hero.title': 'Express. Reflect. Grow.',
    'hero.subtitle': 'Journaling should be as simple as talking. Use voice and leave the rest to us.',
    // Add more translations as needed
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.privacyFocused': 'Privacy-Focused',
    'app.freeTrial': '14-Day Free Trial',
    'features.voiceJournaling.title': 'Voice Journaling',
    'features.voiceJournaling.description': 'Record your thoughts with voice and let SOuLO transcribe and analyze them automatically.',
    'features.aiAnalysis.title': 'AI Analysis',
    'features.aiAnalysis.description': 'Gain insights into your patterns and emotions through advanced AI analysis.',
    'features.emotionalTracking.title': 'Emotional Tracking',
    'features.emotionalTracking.description': 'Visualize your emotional journey over time with interactive charts.',
    'features.aiAssistant.title': 'AI Assistant',
    'features.aiAssistant.description': 'Chat with your journal and get personalized insights from your past entries.',
    'pricing.free': 'Free',
    'pricing.premium': 'Premium',
    'pricing.monthly': 'Monthly',
    'pricing.yearly': 'Yearly',
    'pricing.lifetime': 'Lifetime',
    'pricing.getStarted': 'Get Started',
    'pricing.choosePremium': 'Choose Premium',
    'newsletter.title': 'Stay Updated',
    'newsletter.description': 'Subscribe to our newsletter for product updates, journaling tips, and exclusive content.',
    'newsletter.emailPlaceholder': 'Your email address',
    'newsletter.subscribe': 'Subscribe',
    'privacy.title': 'Your Privacy is Our Priority',
    'privacy.description': 'At SOuLO, we believe that your personal thoughts and feelings should remain private. We\'ve built our platform with privacy at its core.',
    'privacy.learnMore': 'Learn More About Our Privacy',
    'testimonials.title': 'What Our Users Say',
    'testimonials.description': 'Join thousands of people who have transformed their self-reflection practice with SOuLO',
    'howItWorks.title': 'How It Works',
    'howItWorks.description': 'Start your self-discovery journey in three simple steps',
    'howItWorks.step1.title': 'Record Your Thoughts',
    'howItWorks.step1.description': 'Speak freely about your day, feelings, or any thoughts you want to capture. No writing required!',
    'howItWorks.step2.title': 'AI Analyzes Your Entry',
    'howItWorks.step2.description': 'Our AI transcribes your voice and analyzes the emotional patterns and key themes in your entry.',
    'howItWorks.step3.title': 'Gain Personalized Insights',
    'howItWorks.step3.description': 'Discover patterns, track emotional trends over time, and get personalized insights to support your growth.',
    'onboarding.languageSelection.title': 'Choose Your Language',
    'onboarding.languageSelection.description': 'Select your preferred language for the SOuLO experience',
    'onboarding.continue': 'Continue',
    'home.journal': 'Your Journal',
    'home.today': 'Today',
  },
  es: {
    'app.download': 'Descargar',
    'app.tryWebApp': 'Probar App Web',
    'nav.blog': 'Blog',
    'nav.faq': 'Preguntas Frecuentes',
    'hero.title': 'Expresar. Reflexionar. Crecer.',
    'hero.subtitle': 'Llevar un diario debería ser tan simple como hablar. Usa tu voz y déjanos el resto a nosotros.',
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.privacyFocused': 'Centrado en la privacidad',
    'app.freeTrial': 'Prueba gratuita de 14 días',
    'features.voiceJournaling.title': 'Diario de voz',
    'features.voiceJournaling.description': 'Graba tus pensamientos con la voz y deja que SOuLO los transcriba y analice automáticamente.',
    'features.aiAnalysis.title': 'Análisis de IA',
    'features.aiAnalysis.description': 'Obtenga información sobre sus patrones y emociones a través del análisis avanzado de IA.',
    'features.emotionalTracking.title': 'Seguimiento emocional',
    'features.emotionalTracking.description': 'Visualice su viaje emocional a lo largo del tiempo con gráficos interactivos.',
    'features.aiAssistant.title': 'Asistente de IA',
    'features.aiAssistant.description': 'Chatea con tu diario y obtén información personalizada de tus entradas pasadas.',
    'pricing.free': 'Gratis',
    'pricing.premium': 'Premium',
    'pricing.monthly': 'Mensual',
    'pricing.yearly': 'Anual',
    'pricing.lifetime': 'De por vida',
    'pricing.getStarted': 'Empezar',
    'pricing.choosePremium': 'Elegir Premium',
    'newsletter.title': 'Mantente actualizado',
    'newsletter.description': 'Suscríbete a nuestro boletín para recibir actualizaciones de productos, consejos para llevar un diario y contenido exclusivo.',
    'newsletter.emailPlaceholder': 'Tu dirección de correo electrónico',
    'newsletter.subscribe': 'Suscribirse',
    'privacy.title': 'Su privacidad es nuestra prioridad',
    'privacy.description': 'En SOuLO, creemos que sus pensamientos y sentimientos personales deben permanecer privados. Hemos construido nuestra plataforma con la privacidad en su núcleo.',
    'privacy.learnMore': 'Obtenga más información sobre nuestra privacidad',
    'testimonials.title': 'Lo que dicen nuestros usuarios',
    'testimonials.description': 'Únase a miles de personas que han transformado su práctica de autorreflexión con SOuLO',
    'howItWorks.title': 'Cómo funciona',
    'howItWorks.description': 'Comience su viaje de autodescubrimiento en tres sencillos pasos',
    'howItWorks.step1.title': 'Graba tus pensamientos',
    'howItWorks.step1.description': 'Habla libremente sobre tu día, tus sentimientos o cualquier pensamiento que quieras capturar. ¡No se requiere escribir!',
    'howItWorks.step2.title': 'La IA analiza tu entrada',
    'howItWorks.step2.description': 'Nuestra IA transcribe tu voz y analiza los patrones emocionales y los temas clave de tu entrada.',
    'howItWorks.step3.title': 'Obtenga información personalizada',
    'howItWorks.step3.description': 'Descubra patrones, rastree las tendencias emocionales a lo largo del tiempo y obtenga información personalizada para respaldar su crecimiento.',
    'onboarding.languageSelection.title': 'Elige tu idioma',
    'onboarding.languageSelection.description': 'Seleccione su idioma preferido para la experiencia SOuLO',
    'onboarding.continue': 'Continuar',
    'home.journal': 'Tu diario',
    'home.today': 'Hoy',
  },
  // Add translations for other languages
  fr: {
    'app.download': 'Télécharger',
    'app.tryWebApp': 'Essayer l\'App Web',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'hero.title': 'Exprimer. Réfléchir. Grandir.',
    'hero.subtitle': 'Tenir un journal devrait être aussi simple que parler. Utilisez votre voix et laissez-nous faire le reste.',
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.privacyFocused': 'Axé sur la confidentialité',
    'app.freeTrial': 'Essai gratuit de 14 jours',
    'features.voiceJournaling.title': 'Journal vocal',
    'features.voiceJournaling.description': 'Enregistrez vos pensées avec votre voix et laissez SOuLO les transcrire et les analyser automatiquement.',
    'features.aiAnalysis.title': 'Analyse IA',
    'features.aiAnalysis.description': 'Obtenez des informations sur vos schémas et vos émotions grâce à l\'analyse avancée de l\'IA.',
    'features.emotionalTracking.title': 'Suivi émotionnel',
    'features.emotionalTracking.description': 'Visualisez votre parcours émotionnel au fil du temps grâce à des graphiques interactifs.',
    'features.aiAssistant.title': 'Assistant IA',
    'features.aiAssistant.description': 'Discutez avec votre journal et obtenez des informations personnalisées à partir de vos entrées passées.',
    'pricing.free': 'Gratuit',
    'pricing.premium': 'Premium',
    'pricing.monthly': 'Mensuel',
    'pricing.yearly': 'Annuel',
    'pricing.lifetime': 'À vie',
    'pricing.getStarted': 'Commencer',
    'pricing.choosePremium': 'Choisir Premium',
    'newsletter.title': 'Restez à jour',
    'newsletter.description': 'Abonnez-vous à notre newsletter pour recevoir des mises à jour sur les produits, des conseils de journalisation et du contenu exclusif.',
    'newsletter.emailPlaceholder': 'Votre adresse e-mail',
    'newsletter.subscribe': 'S\'abonner',
    'privacy.title': 'Votre vie privée est notre priorité',
    'privacy.description': 'Chez SOuLO, nous pensons que vos pensées et sentiments personnels doivent rester privés. Nous avons construit notre plateforme avec la confidentialité au cœur.',
    'privacy.learnMore': 'En savoir plus sur notre confidentialité',
    'testimonials.title': 'Ce que disent nos utilisateurs',
    'testimonials.description': 'Rejoignez des milliers de personnes qui ont transformé leur pratique d\'autoréflexion avec SOuLO',
    'howItWorks.title': 'Comment ça marche',
    'howItWorks.description': 'Commencez votre voyage de découverte de soi en trois étapes simples',
    'howItWorks.step1.title': 'Enregistrez vos pensées',
    'howItWorks.step1.description': 'Parlez librement de votre journée, de vos sentiments ou de toute pensée que vous souhaitez capturer. Aucune écriture requise!',
    'howItWorks.step2.title': 'L\'IA analyse votre entrée',
    'howItWorks.step2.description': 'Notre IA transcrit votre voix et analyse les schémas émotionnels et les thèmes clés de votre entrée.',
    'howItWorks.step3.title': 'Obtenez des informations personnalisées',
    'howItWorks.step3.description': 'Découvrez des schémas, suivez les tendances émotionnelles au fil du temps et obtenez des informations personnalisées pour soutenir votre croissance.',
    'onboarding.languageSelection.title': 'Choisissez votre langue',
    'onboarding.languageSelection.description': 'Sélectionnez votre langue préférée pour l\'expérience SOuLO',
    'onboarding.continue': 'Continuer',
    'home.journal': 'Votre journal',
    'home.today': 'Aujourd\'hui',
  },
  de: {
    'app.download': 'Herunterladen',
    'app.tryWebApp': 'Web-App ausprobieren',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'hero.title': 'Ausdrücken. Reflektieren. Wachsen.',
    'hero.subtitle': 'Journaling sollte so einfach sein wie Sprechen. Nutze deine Stimme und überlasse uns den Rest.',
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.privacyFocused': 'Datenschutzorientiert',
    'app.freeTrial': '14-tägige kostenlose Testversion',
    'features.voiceJournaling.title': 'Sprachjournaling',
    'features.voiceJournaling.description': 'Nimm deine Gedanken mit deiner Stimme auf und lass SOuLO sie automatisch transkribieren und analysieren.',
    'features.aiAnalysis.title': 'KI-Analyse',
    'features.aiAnalysis.description': 'Gewinne Einblicke in deine Muster und Emotionen durch fortschrittliche KI-Analyse.',
    'features.emotionalTracking.title': 'Emotionale Verfolgung',
    'features.emotionalTracking.description': 'Visualisiere deine emotionale Reise im Laufe der Zeit mit interaktiven Diagrammen.',
    'features.aiAssistant.title': 'KI-Assistent',
    'features.aiAssistant.description': 'Chatte mit deinem Tagebuch und erhalte personalisierte Einblicke aus deinen vergangenen Einträgen.',
    'pricing.free': 'Kostenlos',
    'pricing.premium': 'Premium',
    'pricing.monthly': 'Monatlich',
    'pricing.yearly': 'Jährlich',
    'pricing.lifetime': 'Lebenslang',
    'pricing.getStarted': 'Loslegen',
    'pricing.choosePremium': 'Premium wählen',
    'newsletter.title': 'Bleib auf dem Laufenden',
    'newsletter.description': 'Abonniere unseren Newsletter für Produktupdates, Journaling-Tipps und exklusive Inhalte.',
    'newsletter.emailPlaceholder': 'Deine E-Mail-Adresse',
    'newsletter.subscribe': 'Abonnieren',
    'privacy.title': 'Deine Privatsphäre ist unsere Priorität',
    'privacy.description': 'Bei SOuLO glauben wir, dass deine persönlichen Gedanken und Gefühle privat bleiben sollten. Wir haben unsere Plattform mit Datenschutz als Kern aufgebaut.',
    'privacy.learnMore': 'Erfahre mehr über unseren Datenschutz',
    'testimonials.title': 'Was unsere Nutzer sagen',
    'testimonials.description': 'Schließe dich Tausenden von Menschen an, die ihre Selbstreflexionspraxis mit SOuLO verändert haben',
    'howItWorks.title': 'Wie es funktioniert',
    'howItWorks.description': 'Starte deine Selbstentdeckungsreise in drei einfachen Schritten',
    'howItWorks.step1.title': 'Nimm deine Gedanken auf',
    'howItWorks.step1.description': 'Sprich frei über deinen Tag, deine Gefühle oder alle Gedanken, die du festhalten möchtest. Kein Schreiben erforderlich!',
    'howItWorks.step2.title': 'KI analysiert deinen Eintrag',
    'howItWorks.step2.description': 'Unsere KI transkribiert deine Stimme und analysiert die emotionalen Muster und Schlüsselthemen in deinem Eintrag.',
    'howItWorks.step3.title': 'Gewinne personalisierte Einblicke',
    'howItWorks.step3.description': 'Entdecke Muster, verfolge emotionale Trends im Laufe der Zeit und erhalte personalisierte Einblicke, um dein Wachstum zu unterstützen.',
    'onboarding.languageSelection.title': 'Wähle deine Sprache',
    'onboarding.languageSelection.description': 'Wähle deine bevorzugte Sprache für das SOuLO-Erlebnis',
    'onboarding.continue': 'Fortsetzen',
    'home.journal': 'Dein Journal',
    'home.today': 'Heute',
  },
  zh: {
    'app.download': '下载',
    'app.tryWebApp': '尝试Web应用程序',
    'nav.blog': '博客',
    'nav.faq': '常见问题',
    'hero.title': '表达. 反思. 成长.',
    'hero.subtitle': '写日记应该像说话一样简单. 用声音记录，剩下的交给我们。',
    'app.appStore': '应用商店',
    'app.googlePlay': 'Google Play',
    'app.privacyFocused': '注重隐私',
    'app.freeTrial': '14天免费试用',
    'features.voiceJournaling.title': '语音日记',
    'features.voiceJournaling.description': '用声音记录你的想法，让SOuLO自动转录和分析它们。',
    'features.aiAnalysis.title': '人工智能分析',
    'features.aiAnalysis.description': '通过先进的人工智能分析，深入了解你的模式和情绪。',
    'features.emotionalTracking.title': '情绪追踪',
    'features.emotionalTracking.description': '通过互动图表，可视化你随时间推移的情绪旅程。',
    'features.aiAssistant.title': '人工智能助手',
    'features.aiAssistant.description': '与你的日记聊天，并从你过去的条目中获得个性化的见解。',
    'pricing.free': '免费',
    'pricing.premium': '高级版',
    'pricing.monthly': '每月',
    'pricing.yearly': '每年',
    'pricing.lifetime': '终身',
    'pricing.getStarted': '开始',
    'pricing.choosePremium': '选择高级版',
    'newsletter.title': '保持更新',
    'newsletter.description': '订阅我们的新闻通讯，获取产品更新、日记技巧和独家内容。',
    'newsletter.emailPlaceholder': '你的电子邮件地址',
    'newsletter.subscribe': '订阅',
    'privacy.title': '你的隐私是我们的首要任务',
    'privacy.description': '在SOuLO，我们认为你的个人想法和感受应该保持私密。我们构建平台时，将隐私作为核心。',
    'privacy.learnMore': '了解更多关于我们的隐私',
    'testimonials.title': '我们的用户怎么说',
    'testimonials.description': '加入成千上万通过SOuLO改变了自我反思实践的人们',
    'howItWorks.title': '它是如何工作的',
    'howItWorks.description': '通过三个简单的步骤开始你的自我发现之旅',
    'howItWorks.step1.title': '记录你的想法',
    'howItWorks.step1.description': '自由地谈论你的一天、感受或任何你想捕捉的想法。无需写作！',
    'howItWorks.step2.title': '人工智能分析你的条目',
    'howItWorks.step2.description': '我们的人工智能转录你的声音，并分析你条目中的情绪模式和关键主题。',
    'howItWorks.step3.title': '获得个性化的见解',
    'howItWorks.step3.description': '发现模式，跟踪随时间推移的情绪趋势，并获得个性化的见解来支持你的成长。',
    'onboarding.languageSelection.title': '选择你的语言',
    'onboarding.languageSelection.description': '为SOuLO体验选择你喜欢的语言',
    'onboarding.continue': '继续',
    'home.journal': '你的日记',
    'home.today': '今天',
  },
  hi: {
    'app.download': 'डाउनलोड',
    'app.tryWebApp': 'वेब ऐप आज़माएं',
    'nav.blog': 'ब्लॉग',
    'nav.faq': 'सामान्य प्रश्न',
    'hero.title': 'व्यक्त करें. प्रतिबिंबित करें. बढ़ें.',
    'hero.subtitle': 'जर्नलिंग बात करने जितना आसान होना चाहिए. आवाज का प्रयोग करें और बाकी हम पर छोड़ दें।',
    'app.appStore': 'ऐप स्टोर',
    'app.googlePlay': 'गूगल प्ले',
    'app.privacyFocused': 'गोपनीयता-केंद्रित',
    'app.freeTrial': '14-दिन का निःशुल्क परीक्षण',
    'features.voiceJournaling.title': 'वॉयस जर्नलिंग',
    'features.voiceJournaling.description': 'आवाज के साथ अपने विचारों को रिकॉर्ड करें और SOuLO को स्वचालित रूप से ट्रांसक्राइब और विश्लेषण करने दें।',
    'features.aiAnalysis.title': 'एआई विश्लेषण',
    'features.aiAnalysis.description': 'उन्नत एआई विश्लेषण के माध्यम से अपने पैटर्न और भावनाओं में अंतर्दृष्टि प्राप्त करें।',
    'features.emotionalTracking.title': 'भावनात्मक ट्रैकिंग',
    'features.emotionalTracking.description': 'इंटरैक्टिव चार्ट के साथ समय के साथ अपनी भावनात्मक यात्रा की कल्पना करें।',
    'features.aiAssistant.title': 'एआई सहायक',
    'features.aiAssistant.description': 'अपनी पत्रिका के साथ चैट करें और अपनी पिछली प्रविष्टियों से व्यक्तिगत अंतर्दृष्टि प्राप्त करें।',
    'pricing.free': 'मुफ्त',
    'pricing.premium': 'प्रीमियम',
    'pricing.monthly': 'मासिक',
    'pricing.yearly': 'वार्षिक',
    'pricing.lifetime': 'आजीवन',
    'pricing.getStarted': 'शुरू हो जाओ',
    'pricing.choosePremium': 'प्रीमियम चुनें',
    'newsletter.title': 'अपडेट रहें',
    'newsletter.description': 'उत्पाद अपडेट, जर्नलिंग टिप्स और विशेष सामग्री के लिए हमारे न्यूज़लेटर की सदस्यता लें।',
    'newsletter.emailPlaceholder': 'आपका ईमेल पता',
    'newsletter.subscribe': 'सदस्यता लें',
    'privacy.title': 'आपकी गोपनीयता हमारी प्राथमिकता है',
    'privacy.description': 'SOuLO में, हम मानते हैं कि आपके व्यक्तिगत विचार और भावनाएँ निजी रहनी चाहिए। हमने अपने प्लेटफ़ॉर्म को गोपनीयता को ध्यान में रखकर बनाया है।',
    'privacy.learnMore': 'हमारी गोपनीयता के बारे में अधिक जानें',
    'testimonials.title': 'हमारे उपयोगकर्ता क्या कहते हैं',
    'testimonials.description': 'हजारों लोगों से जुड़ें जिन्होंने SOuLO के साथ अपने आत्म-चिंतन अभ्यास को बदल दिया है',
    'howItWorks.title': 'यह कैसे काम करता है',
    'howItWorks.description': 'तीन सरल चरणों में अपनी आत्म-खोज यात्रा शुरू करें',
    'howItWorks.step1.title': 'अपने विचार रिकॉर्ड करें',
    'howItWorks.step1.description': 'अपने दिन, भावनाओं या किसी भी विचार के बारे में खुलकर बात करें जिसे आप कैद करना चाहते हैं। लिखने की आवश्यकता नहीं है!',
    'howItWorks.step2.title': 'एआई आपकी प्रविष्टि का विश्लेषण करता है',
    'howItWorks.step2.description': 'हमारी एआई आपकी आवाज को ट्रांसक्राइब करती है और आपकी प्रविष्टि में भावनात्मक पैटर्न और प्रमुख विषयों का विश्लेषण करती है।',
    'howItWorks.step3.title': 'व्यक्तिगत अंतर्दृष्टि प्राप्त करें',
    'howItWorks.step3.description': 'पैटर्न खोजें, समय के साथ भावनात्मक रुझानों को ट्रैक करें और अपनी वृद्धि का समर्थन करने के लिए व्यक्तिगत अंतर्दृष्टि प्राप्त करें।',
    'onboarding.languageSelection.title': 'अपनी भाषा चुनें',
    'onboarding.languageSelection.description': 'SOuLO अनुभव के लिए अपनी पसंदीदा भाषा चुनें',
    'onboarding.continue': 'जारी रखें',
    'home.journal': 'आपकी पत्रिका',
    'home.today': 'आज',
  },
  ja: {
    'app.download': 'ダウンロード',
    'app.tryWebApp': 'ウェブアプリを試す',
    'nav.blog': 'ブログ',
    'nav.faq': 'よくある質問',
    'hero.title': '表現。 反省。 成長。',
    'hero.subtitle': 'ジャーナリングは話すのと同じくらい簡単であるべきです。 音声を使って、残りは私たちにお任せください。',
    'app.appStore': 'アプリストア',
    'app.googlePlay': 'グーグルプレイ',
    'app.privacyFocused': 'プライバシー重視',
    'app.freeTrial': '14日間の無料トライアル',
    'features.voiceJournaling.title': '音声ジャーナリング',
    'features.voiceJournaling.description': '音声であなたの考えを記録し、SOuLOに自動的に文字起こしと分析を任せましょう。',
    'features.aiAnalysis.title': 'AI分析',
    'features.aiAnalysis.description': '高度なAI分析を通じて、あなたのパターンと感情についての洞察を得てください。',
    'features.emotionalTracking.title': '感情追跡',
    'features.emotionalTracking.description': 'インタラクティブなグラフで、時間の経過に伴うあなたの感情的な旅を視覚化します。',
    'features.aiAssistant.title': 'AIアシスタント',
    'features.aiAssistant.description': 'あなたのジャーナルとチャットし、過去のエントリからパーソナライズされた洞察を得てください。',
    'pricing.free': '無料',
    'pricing.premium': 'プレミアム',
    'pricing.monthly': '月額',
    'pricing.yearly': '年額',
    'pricing.lifetime': '生涯',
    'pricing.getStarted': '始める',
    'pricing.choosePremium': 'プレミアムを選択',
    'newsletter.title': '最新情報をお届け',
    'newsletter.description': '製品のアップデート、ジャーナリングのヒント、および限定コンテンツについては、ニュースレターを購読してください。',
    'newsletter.emailPlaceholder': 'あなたのメールアドレス',
    'newsletter.subscribe': '購読する',
    'privacy.title': 'あなたのプライバシーは私たちの優先事項です',
    'privacy.description': 'SOuLOでは、あなたの個人的な考えや感情はプライベートに保たれるべきだと考えています。 私たちはプライバシーを核としてプラットフォームを構築しました。',
    'privacy.learnMore': '私たちのプライバシーについてもっと学ぶ',
    'testimonials.title': 'ユーザーの声',
    'testimonials.description': 'SOuLOで自己反省の実践を変革した何千人もの人々に加わってください',
    'howItWorks.title': 'どのように機能するか',
    'howItWorks.description': '3つの簡単なステップで自己発見の旅を始めましょう',
    'howItWorks.step1.title': 'あなたの考えを記録する',
    'howItWorks.step1.description': 'あなたの日、感情、またはあなたが捉えたいどんな考えについても自由に話してください。 書く必要はありません！',
    'howItWorks.step2.title': 'AIがあなたのエントリを分析します',
    'howItWorks.step2.description': '私たちのAIはあなたの声を文字起こしし、あなたのエントリの感情的なパターンと主要なテーマを分析します。',
    'howItWorks.step3.title': 'パーソナライズされた洞察を得る',
    'howItWorks.step3.description': 'パターンを発見し、時間の経過に伴う感情的な傾向を追跡し、あなたの成長をサポートするためにパーソナライズされた洞察を得てください。',
    'onboarding.languageSelection.title': '言語を選択してください',
    'onboarding.languageSelection.description': 'SOuLO体験のためにあなたの好みの言語を選択してください',
    'onboarding.continue': '続ける',
    'home.journal': 'あなたのジャーナル',
    'home.today': '今日',
  },
  ko: {
    'app.download': '다운로드',
    'app.tryWebApp': '웹 앱 사용해보기',
    'nav.blog': '블로그',
    'nav.faq': '자주 묻는 질문',
    'hero.title': '표현하세요. 반성하세요. 성장하세요.',
    'hero.subtitle': '저널링은 말하는 것만큼 쉬워야 합니다. 음성을 사용하고 나머지는 저희에게 맡기세요.',
    'app.appStore': '앱 스토어',
    'app.googlePlay': '구글 플레이',
    'app.privacyFocused': '개인 정보 보호 중심',
    'app.freeTrial': '14일 무료 평가판',
    'features.voiceJournaling.title': '음성 저널링',
    'features.voiceJournaling.description': '음성으로 생각을 기록하고 SOuLO가 자동으로 필사하고 분석하도록 하세요.',
    'features.aiAnalysis.title': 'AI 분석',
    'features.aiAnalysis.description': '고급 AI 분석을 통해 패턴과 감정에 대한 통찰력을 얻으세요.',
    'features.emotionalTracking.title': '감정 추적',
    'features.emotionalTracking.description': '대화형 차트를 통해 시간 경과에 따른 감정적 여정을 시각화하세요.',
    'features.aiAssistant.title': 'AI 어시스턴트',
    'features.aiAssistant.description': '저널과 채팅하고 과거 항목에서 개인화된 통찰력을 얻으세요.',
    'pricing.free': '무료',
    'pricing.premium': '프리미엄',
    'pricing.monthly': '월간',
    'pricing.yearly': '연간',
    'pricing.lifetime': '평생',
    'pricing.getStarted': '시작하기',
    'pricing.choosePremium': '프리미엄 선택',
    'newsletter.title': '최신 정보 유지',
    'newsletter.description': '제품 업데이트, 저널링 팁 및 독점 콘텐츠를 보려면 뉴스레터를 구독하세요.',
    'newsletter.emailPlaceholder': '귀하의 이메일 주소',
    'newsletter.subscribe': '구독하기',
    'privacy.title': '귀하의 개인 정보 보호가 최우선입니다',
    'privacy.description': 'SOuLO에서는 귀하의 개인적인 생각과 감정이 비공개로 유지되어야 한다고 믿습니다. 저희는 개인 정보 보호를 핵심으로 플랫폼을 구축했습니다.',
    'privacy.learnMore': '개인 정보 보호에 대해 자세히 알아보세요',
    'testimonials.title': '사용자 후기',
    'testimonials.description': 'SOuLO로 자기 성찰 연습을 변화시킨 수천 명의 사람들과 함께하세요',
    'howItWorks.title': '작동 방식',
    'howItWorks.description': '세 가지 간단한 단계를 통해 자기 발견 여정을 시작하세요',
    'howItWorks.step1.title': '생각 기록하기',
    'howItWorks.step1.description': '하루, 감정 또는 캡처하려는 모든 생각에 대해 자유롭게 이야기하세요. 글쓰기가 필요하지 않습니다!',
    'howItWorks.step2.title': 'AI가 항목 분석',
    'howItWorks.step2.description': '저희 AI는 귀하의 음성을 필사하고 귀하의 항목에서 감정적 패턴과 주요 테마를 분석합니다.',
    'howItWorks.step3.title': '개인화된 통찰력 얻기',
    'howItWorks.step3.description': '패턴을 발견하고, 시간 경과에 따른 감정적 추세를 추적하고, 성장을 지원하기 위해 개인화된 통찰력을 얻으세요.',
    'onboarding.languageSelection.title': '언어 선택',
    'onboarding.languageSelection.description': 'SOuLO 경험에 선호하는 언어를 선택하세요',
    'onboarding.continue': '계속',
    'home.journal': '당신의 저널',
    'home.today': '오늘',
  },
  ru: {
    'app.download': 'Скачать',
    'app.tryWebApp': 'Попробовать веб-приложение',
    'nav.blog': 'Блог',
    'nav.faq': 'Часто задаваемые вопросы',
    'hero.title': 'Выражайте. Размышляйте. Растите.',
    'hero.subtitle': 'Ведение дневника должно быть таким же простым, как разговор. Используйте голос, а остальное предоставьте нам.',
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.privacyFocused': 'Ориентирован на конфиденциальность',
    'app.freeTrial': '14-дневная бесплатная пробная версия',
    'features.voiceJournaling.title': 'Голосовой дневник',
    'features.voiceJournaling.description': 'Записывайте свои мысли голосом, и пусть SOuLO автоматически расшифрует и проанализирует их.',
    'features.aiAnalysis.title': 'Анализ ИИ',
    'features.aiAnalysis.description': 'Получите представление о своих моделях и эмоциях с помощью расширенного анализа ИИ.',
    'features.emotionalTracking.title': 'Отслеживание эмоций',
    'features.emotionalTracking.description': 'Визуализируйте свое эмоциональное путешествие во времени с помощью интерактивных графиков.',
    'features.aiAssistant.title': 'ИИ-помощник',
    'features.aiAssistant.description': 'Общайтесь со своим дневником и получайте персональные сведения из своих прошлых записей.',
    'pricing.free': 'Бесплатно',
    'pricing.premium': 'Премиум',
    'pricing.monthly': 'Ежемесячно',
    'pricing.yearly': 'Ежегодно',
    'pricing.lifetime': 'Пожизненно',
    'pricing.getStarted': 'Начать',
    'pricing.choosePremium': 'Выбрать Премиум',
    'newsletter.title': 'Будьте в курсе',
    'newsletter.description': 'Подпишитесь на нашу рассылку, чтобы получать обновления о продуктах, советы по ведению дневника и эксклюзивный контент.',
    'newsletter.emailPlaceholder': 'Ваш адрес электронной почты',
    'newsletter.subscribe': 'Подписаться',
    'privacy.title': 'Ваша конфиденциальность — наш приоритет',
    'privacy.description': 'В SOuLO мы считаем, что ваши личные мысли и чувства должны оставаться конфиденциальными. Мы построили нашу платформу с учетом конфиденциальности.',
    'privacy.learnMore': 'Узнайте больше о нашей конфиденциальности',
    'testimonials.title': 'Что говорят наши пользователи',
    'testimonials.description': 'Присоединяйтесь к тысячам людей, которые изменили свою практику самоанализа с помощью SOuLO',
    'howItWorks.title': 'Как это работает',
    'howItWorks.description': 'Начните свой путь самопознания в три простых шага',
    'howItWorks.step1.title': 'Запишите свои мысли',
    'howItWorks.step1.description': 'Говорите свободно о своем дне, чувствах или любых мыслях, которые вы хотите записать. Писать не нужно!',
    'howItWorks.step2.title': 'ИИ анализирует вашу запись',
    'howItWorks.step2.description': 'Наш ИИ расшифровывает ваш голос и анализирует эмоциональные шаблоны и ключевые темы в вашей записи.',
    'howItWorks.step3.title': 'Получите персонализированные выводы',
    'howItWorks.step3.description': 'Обнаружите закономерности, отслеживайте эмоциональные тенденции со временем и получайте индивидуальные выводы для поддержки вашего роста.',
    'onboarding.languageSelection.title': 'Выберите ваш язык',
    'onboarding.languageSelection.description': 'Выберите предпочитаемый язык для работы с SOuLO',
    'onboarding.continue': 'Продолжить',
    'home.journal': 'Ваш дневник',
    'home.today': 'Сегодня',
  },
  pt: {
    'app.download': 'Baixar',
    'app.tryWebApp': 'Experimentar App Web',
    'nav.blog': 'Blog',
    'nav.faq': 'Perguntas Frequentes',
    'hero.title': 'Expressar. Refletir. Crescer.',
    'hero.subtitle': 'Fazer um diário deve ser tão simples quanto falar. Use a voz e deixe o resto conosco.',
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.privacyFocused': 'Focado em privacidade',
    'app.freeTrial': 'Teste gratuito de 14 dias',
    'features.voiceJournaling.title': 'Diário por voz',
    'features.voiceJournaling.description': 'Grave seus pensamentos com a voz e deixe o SOuLO transcrevê-los e analisá-los automaticamente.',
    'features.aiAnalysis.title': 'Análise de IA',
    'features.aiAnalysis.description': 'Obtenha insights sobre seus padrões e emoções através da análise avançada de IA.',
    'features.emotionalTracking.title': 'Acompanhamento emocional',
    'features.emotionalTracking.description': 'Visualize sua jornada emocional ao longo do tempo com gráficos interativos.',
    'features.aiAssistant.title': 'Assistente de IA',
    'features.aiAssistant.description': 'Converse com seu diário e obtenha insights personalizados das suas entradas passadas.',
    'pricing.free': 'Gratuito',
    'pricing.premium': 'Premium',
    'pricing.monthly': 'Mensal',
    'pricing.yearly': 'Anual',
    'pricing.lifetime': 'Vitalício',
    'pricing.getStarted': 'Começar',
    'pricing.choosePremium': 'Escolher Premium',
    'newsletter.title': 'Mantenha-se atualizado',
    'newsletter.description': 'Inscreva-se em nossa newsletter para receber atualizações do produto, dicas de diário e conteúdo exclusivo.',
    'newsletter.emailPlaceholder': 'Seu endereço de e-mail',
    'newsletter.subscribe': 'Inscrever-se',
    'privacy.title': 'Sua privacidade é nossa prioridade',
    'privacy.description': 'No SOuLO, acreditamos que seus pensamentos e sentimentos pessoais devem permanecer privados. Construímos nossa plataforma com a privacidade em seu núcleo.',
    'privacy.learnMore': 'Saiba mais sobre nossa privacidade',
    'testimonials.title': 'O que nossos usuários dizem',
    'testimonials.description': 'Junte-se a milhares de pessoas que transformaram sua prática de autorreflexão com o SOuLO',
    'howItWorks.title': 'Como funciona',
    'howItWorks.description': 'Comece sua jornada de autodescoberta em três passos simples',
    'howItWorks.step1.title': 'Grave seus pensamentos',
    'howItWorks.step1.description': 'Fale livremente sobre seu dia, sentimentos ou quaisquer pensamentos que deseje capturar. Não é necessário escrever!',
    'howItWorks.step2.title': 'A IA analisa sua entrada',
    'howItWorks.step2.description': 'Nossa IA transcreve sua voz e analisa os padrões emocionais e temas-chave em sua entrada.',
    'howItWorks.step3.title': 'Obtenha insights personalizados',
    'howItWorks.step3.description': 'Descubra padrões, acompanhe tendências emocionais ao longo do tempo e obtenha insights personalizados para apoiar seu crescimento.',
    'onboarding.languageSelection.title': 'Escolha seu idioma',
    'onboarding.languageSelection.description': 'Selecione seu idioma preferido para a experiência SOuLO',
    'onboarding.continue': 'Continuar',
    'home.journal': 'Seu diário',
    'home.today': 'Hoje',
  }
};

// Create the LanguageProvider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Try to get the saved language from localStorage, or use browser language, or default to English
  const getSavedLanguage = (): LanguageCode => {
    // First check if we have a saved language preference
    const savedLanguage = localStorage.getItem('preferredLanguage');
    if (savedLanguage && Object.keys(SUPPORTED_LANGUAGES).includes(savedLanguage)) {
      return savedLanguage as LanguageCode;
    }
    
    // Try to detect browser language
    const browserLang = navigator.language.split('-')[0];
    if (browserLang && Object.keys(SUPPORTED_LANGUAGES).includes(browserLang)) {
      return browserLang as LanguageCode;
    }
    
    // Default to English
    return 'en';
  };
  
  const [language, setLanguage] = useState<LanguageCode>(getSavedLanguage());
  
  // Save language preference to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);
  
  // Translation function
  const translate = (key: string, fallback?: string): string => {
    // First try to get a translation in the current language
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    
    // If not found and not English, try English as fallback
    if (language !== 'en' && translations.en && translations.en[key]) {
      return translations.en[key];
    }
    
    // Return fallback or key if all else fails
    return fallback || key;
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook for consuming the language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
